# Generated by Django 5.2 on 2025-04-26 01:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pin',
            name='webURL',
            field=models.URLField(blank=True, null=True),
        ),
    ]
