# Generated by Django 5.2 on 2025-04-28 16:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0002_alter_pin_weburl'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='board',
            field=models.ForeignKey(default=113, on_delete=django.db.models.deletion.CASCADE, to='backend.board'),
            preserve_default=False,
        ),
    ]
