# Generated by Django 5.2 on 2025-04-29 00:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0003_comment_board'),
    ]

    operations = [
        migrations.AddField(
            model_name='followstream',
            name='streamName',
            field=models.CharField(default='', max_length=255),
            preserve_default=False,
        ),
        migrations.AddConstraint(
            model_name='followstream',
            constraint=models.UniqueConstraint(fields=('user', 'streamName'), name='unique_user_stream'),
        ),
    ]
