# Generated by Django 5.2 on 2025-05-07 03:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0004_followstream_streamname_and_more'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='board',
            name='unique_user_board',
        ),
        migrations.RemoveConstraint(
            model_name='followstream',
            name='unique_user_stream',
        ),
        migrations.RemoveConstraint(
            model_name='streams',
            name='unique_fs_board',
        ),
        migrations.RenameField(
            model_name='board',
            old_name='boardName',
            new_name='boardname',
        ),
        migrations.RenameField(
            model_name='board',
            old_name='friendsOnlyComments',
            new_name='friendsonlycomments',
        ),
        migrations.RenameField(
            model_name='followstream',
            old_name='streamName',
            new_name='streamname',
        ),
        migrations.RenameField(
            model_name='pin',
            old_name='imageURL',
            new_name='imageurl',
        ),
        migrations.RenameField(
            model_name='pin',
            old_name='webURL',
            new_name='weburl',
        ),
        migrations.RenameField(
            model_name='streams',
            old_name='followStream',
            new_name='followstream',
        ),
        migrations.AlterField(
            model_name='likes',
            name='pin',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='likes', to='backend.pin'),
        ),
        migrations.AddConstraint(
            model_name='board',
            constraint=models.UniqueConstraint(fields=('user', 'boardname'), name='unique_user_board'),
        ),
        migrations.AddConstraint(
            model_name='followstream',
            constraint=models.UniqueConstraint(fields=('user', 'streamname'), name='unique_user_stream'),
        ),
        migrations.AddConstraint(
            model_name='streams',
            constraint=models.UniqueConstraint(fields=('followstream', 'board'), name='unique_fs_board'),
        ),
    ]
